-- Seed the FAQ table from the copy that was hard-coded in the
-- templates, so Thushara owns every question and answer from
-- /admin/faq. Anything whose answer was still a note to the
-- developer is seeded empty and unpublished: it appears on his
-- worklist and never on the site.

INSERT OR IGNORE INTO faqs (question, answer, category, service, published, sort_order) VALUES
  ('Do I need this if my employer already has cover?', '', NULL, 'professional-indemnity', 0, 1),
  ('What isn''t covered?', '', NULL, 'professional-indemnity', 0, 2),
  ('How quickly can cover start?', '', NULL, 'professional-indemnity', 0, 3),
  ('What happens if I change profession?', '', NULL, 'professional-indemnity', 0, 4),
  ('What''s the difference between comprehensive and third-party?', '', NULL, 'motor-insurance', 0, 5),
  ('How is my premium worked out?', '', NULL, 'motor-insurance', 0, 6),
  ('What happens to my no-claims bonus if I claim?', '', NULL, 'motor-insurance', 0, 7),
  ('Can I insure a vehicle I''ve just bought?', '', NULL, 'motor-insurance', 0, 8),
  ('How much cover does my family actually need?', '', NULL, 'life-income-protection', 0, 9),
  ('What''s the difference between this and a lump sum policy?', '', NULL, 'life-income-protection', 0, 10),
  ('What happens if my circumstances change?', '', NULL, 'life-income-protection', 0, 11),
  ('Are pre-existing conditions covered?', '', NULL, 'health-insurance', 0, 12),
  ('Which hospitals can I use?', '', NULL, 'health-insurance', 0, 13),
  ('Can I add my parents or children?', '', NULL, 'health-insurance', 0, 14),
  ('What happens if I can''t keep up the payments?', '', NULL, 'children-education', 0, 15),
  ('Can I use the money for something other than education?', '', NULL, 'children-education', 0, 16),
  ('When should I start?', '', NULL, 'children-education', 0, 17),
  ('I''m 28 — isn''t this far too early?', '', NULL, 'retirement-plan', 0, 18),
  ('What if I need the money before retirement?', '', NULL, 'retirement-plan', 0, 19),
  ('How does this sit alongside EPF and ETF?', '', NULL, 'retirement-plan', 0, 20),
  ('How do I work out the right sum insured?', '', NULL, 'house-property', 0, 21),
  ('Am I covered for flood and landslide?', '', NULL, 'house-property', 0, 22),
  ('Does this cover a property I rent out?', '', NULL, 'house-property', 0, 23),
  ('My university asks for proof of cover — can you provide it?', '', NULL, 'travel-insurance', 0, 24),
  ('How quickly can cover be arranged?', '', NULL, 'travel-insurance', 0, 25),
  ('Does it cover pre-existing medical conditions?', '', NULL, 'travel-insurance', 0, 26),
  ('Are you going to pressure me into buying something?', 'No. The first conversation is twenty to thirty minutes and ends with no decision required. I come back to you in writing with options, and one of those options is always doing nothing if that is genuinely the right answer for where you are.', 'Getting started', NULL, 1, 27),
  ('How are you paid?', '', 'Getting started', NULL, 0, 28),
  ('What does the first conversation actually involve?', 'I ask about your situation, your family, and your plans. You are not asked to decide anything, bring anything, or prepare anything. If it turns out you do not need cover right now, I will say so.', 'Getting started', NULL, 1, 29),
  ('Why use an advisor instead of buying online?', '', 'Getting started', NULL, 0, 30),
  ('What if I already have cover through my employer?', '', 'Getting started', NULL, 0, 31),
  ('What is MDRT, and why does it matter?', 'The Million Dollar Round Table is a global association of financial professionals, founded in 1927. Membership is earned annually on production, ethics and professional conduct — it cannot be bought. Fewer than one percent of the world''s advisors qualify in any given year.', 'About Thushara', NULL, 1, 32),
  ('Do you work with people outside Colombo?', 'Yes. I am based in Colombo and travel island-wide for clients. Most first conversations happen by phone or WhatsApp regardless of where you are.', 'About Thushara', NULL, 1, 33),
  ('Are you tied to Sri Lanka Insurance Corporation?', '', 'About Thushara', NULL, 0, 34),
  ('What happens if my claim is rejected?', '', 'Claims', NULL, 0, 35),
  ('Do you decide whether my claim is paid?', 'No. Claims are assessed and paid by Sri Lanka Insurance Corporation. I am a consultant, not the insurer. What I do is make sure your claim is presented correctly, chase it through the assessment, and keep you informed — which is worth more than most people expect.', 'Claims', NULL, 1, 36),
  ('What should I do first when something happens?', 'Call me, before filling in any form. I will tell you exactly which documents are needed and in what order, then prepare and submit the paperwork on your behalf.', 'Claims', NULL, 1, 37),
  ('What''s the difference between comprehensive and third-party?', '', 'Motor', NULL, 0, 38),
  ('How is my premium calculated?', '', 'Motor', NULL, 0, 39),
  ('What happens to my no-claims bonus if I claim?', '', 'Motor', NULL, 0, 40),
  ('How much cover does my family actually need?', '', 'Life & Income Protection', NULL, 0, 41),
  ('What is the difference between a lump sum and income protection?', 'Income protection pays your family a regular monthly income rather than one lump sum. A lump sum has to be managed and can be spent; an income simply keeps arriving.', 'Life & Income Protection', NULL, 1, 42),
  ('Are pre-existing conditions covered?', '', 'Health', NULL, 0, 43),
  ('Which hospitals can I use?', '', 'Health', NULL, 0, 44),
  ('Do I need this if my employer already has cover?', '', 'Professional Indemnity', NULL, 0, 45),
  ('What isn''t covered?', '', 'Professional Indemnity', NULL, 0, 46),
  ('What happens if I cannot keep up the payments?', '', 'Education & Retirement', NULL, 0, 47),
  ('I''m 28. Isn''t a retirement plan far too early?', '', 'Education & Retirement', NULL, 0, 48),
  ('My university asks for proof of cover. Can you provide it?', '', 'Travel', NULL, 0, 49),
  ('How quickly can cover be arranged?', '', 'Travel', NULL, 0, 50),
  ('How do I work out the right sum insured?', '', 'Property', NULL, 0, 51),
  ('Am I covered for flood and landslide?', '', 'Property', NULL, 0, 52),
  ('How do I pay, and how often?', '', 'Premiums & payments', NULL, 0, 53),
  ('What happens if I miss a payment?', '', 'Premiums & payments', NULL, 0, 54),
  ('What do you do with my details?', 'They are used to contact you about your enquiry and nothing else. They are never sold or shared with third parties for marketing. You can ask me to delete them at any time.', 'Privacy', NULL, 1, 55);
